### ISSUE TITLE
下面是我测试的报错。

### ISSUE THREAD

**Issue by tdtc7** [chaudharyarjun/LooneyPwner#1]
jenkins@63aae1be8cb7:/tmp$ ./loo
./looneypwner.sh
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
./looneypwner.sh: line 1: payload:allShortcutsEnabled:false: command not found

**Comment by opabravo** [comment]
Try `export TERM=xterm`
